stages:
  - deploy

deploy_job:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$ENV_API" > .env.api
    - echo "$ENV_WATCHER" > .env.watcher

    - docker compose up -d --build --remove-orphans

    - docker compose ps
  only:
    - master
