stages:
  - test
  - deploy

test_job:
  stage: test
  image: golang:1.26-alpine
  script:
    - apk add --no-cache build-base
    - CGO_ENABLED=1 go test -v ./...
  only:
    - master
    - merge_requests

deploy_job:
  stage: deploy
  image: docker:latest
  variables:
      DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - echo "$ENV_API" > .env.api
    - echo "$ENV_WATCHER" > .env.watcher

    - docker compose up -d --build --remove-orphans

    - docker compose ps
  only:
    - master