services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_balancer
    image: uptime_checker_nginx:latest
    ports:
      - "80:80"
    depends_on:
      api:
        condition:
          service_started
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    restart: always
    env_file:
      - .env.api
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network
      - back-network
    deploy:
      replicas: 2

  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_DB: uptime_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d uptime_db"]

  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: "4L6699E8HK92B694319692"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LOG4J_LOGGERS: "org.apache.kafka=ERROR,kafka=ERROR"

      KAFKA_LOG_RETENTION_HOURS: 1

    networks:
      - back-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]

  watcher:
    build:
      context: .
      dockerfile: cmd/watcher/Dockerfile
    env_file:
      - .env.watcher
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - back-network
    deploy:
      replicas: 3

networks:
  app-network:
    driver: bridge
  back-network:
    internal: true

volumes:
  db_data:
