worker_processes auto;
worker_rlimit_nofile 2048;

events {
worker_connections 1024;
}

http {
    server_tokens off;
    upstream api_cluster {
        server api:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_cluster;

            proxy_set_header Host              "$host";
            proxy_set_header X-Real-IP         "$remote_addr";
            proxy_set_header X-Forwarded-For   "$proxy_add_x_forwarded_for";
            proxy_set_header X-Forwarded-Proto "$scheme";

            proxy_connect_timeout 5s;
            proxy_send_timeout 10s;
            proxy_read_timeout 10s;
        }
    }
}